language: ruby
rvm:
 - 2.3
 - jruby
 - rbx-3
services:
 - redis-server
 - postgresql
before_script:
 - psql -c 'create database travis_ci_test;' -U postgres
 - cp config/database.yml.travis config/database.yml
script:
 - bin/rake db:migrate RAILS_ENV=test
 - bin/rake assets:precompile
 - bin/rake
addons:
  chrome: stable
