---
language: ruby
rvm:
   - 2.3
services:
   - docker
before_script:
   - docker-compose up --build
script:
   - docker-compose exec web bin/rake db:create db:migrate RAILS_ENV=test
   - bin/rake
addons:
   chrome: stable
