---
language: ruby
services:
   - docker
before_script:
   - docker-compose build
script:
   - docker-compose up -d
   - docker-compose exec web bin/rake db:create db:migrate RAILS_ENV=test
   - docker-compose stop
   - docker-compose up
addons:
   chrome: stable
