version: '3'

services:
  db:
    image: postgres
    expose:
    - 5432
  website:
    build: .
    environment:
    - "SECRET_KEY_BASE=sssss"
    command:  bundle exec  rails s -p 3000 -b '0.0.0.0'
    ports:
      - '3000:3000'
    volumes:
      - '.:/ozean'
    env_file:
      - '.env'
    depends_on:
      - db
    links:
    - db:db
