defaults: &defaults
  imap_server: "webmail.henrixapp.com"
  imap_port: 993
  use_ssl: true
  ignore_ssl_error: false
  email: "pruefungsberichte@henrixapp.com"
  password: "test123456"
  box: "INBOX"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
